import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import SocketProvider from "../providers/socket-provider";
import { Toaster } from "@/components/ui/sonner";
import TanstackQueryProvider from "@/providers/tanstackquery-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <TanstackQueryProvider>
          {/* <SocketProvider socketUrl={process.env.SOCKET_URL as string}> */}
          {children}
          {/* </SocketProvider> */}
        </TanstackQueryProvider>
        <Toaster
          position="top-right"
          richColors
          duration={1000}
          expand={true}
        />
      </body>
    </html>
  );
}
