services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    env_file:
      - .env
    ports:
      - "6379:6379"
