# Use the official Node.js image as the base image
FROM node:22

# Set the working directory
WORKDIR /usr/src/app

# Copy all files from the current directory to the working directory
COPY . .

# Install dependencies
RUN npm install


# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "run", "start:dev"]